HW4: Homework3.o Functions3.o
	cc -o HW4 Homework3.o Functions3.o
Functions3.o: Structuredeclarations.h MenuFunctionPrototypes.h
	cc -c Functions3.c
Homework3.o: Structuredeclarations.h
	cc -c Homework3.c
clean: 
	$(RM) HW4 *.o *~                                          
